version: '3.8'

services:
  nextjs:
    build:
      dockerfile: Dockerfile.dev
    container_name: nextjs
    restart: always
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jobs

  redis:
    image: redis:latest
    profiles: [development]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
    driver: local
